### ISSUE TITLE
Call over HTTPS instead of HTTP

### ISSUE THREAD

**Issue by insquared** [YourFavouriteOreo/VTT-Chat-GIFs#1]
![chrome_IwWJvIMqNG](https://user-images.githubusercontent.com/74970976/121412414-b066b180-c932-11eb-9840-4fbdbdb31611.png)

I think calling the API over HTTPS would be better, so that people that are using third-party hosts like Forge, Molten and etc. could use the plugin.

**Comment by insquared** [comment]
What is happening is the module is requesting an insecure server (HTTP not HTTPS) and the browser is preventing this from happening.  The reason it works locally, I think, is the browser disables some protections when you're accessing a local server (localhost).

**Comment by YourFavouriteOreo** [comment]
Just released 1.0.1 to address this concern , it now accesses giphy via https . Let me know if the issue does not dissipate. Closing for now
