### ISSUE TITLE
1.0.4 still pointing at 1.0.2 zip release

### ISSUE THREAD

**Issue by tehguitarist** [YourFavouriteOreo/VTT-Chat-GIFs#11]
Subject says it all really, just a quick change to the module.json and a new release needs to be made up.

**Comment by YourFavouriteOreo** [comment]
Just saw this and wanted to build it but it was built in node-sass looking for a way to get that to work as node-sass doesnt support ARM cpus and it was deprecated so that support is unlikely to come

**Comment by tehguitarist** [comment]
Found this which might be helpful: https://stackoverflow.com/questions/68095626/node-sass-with-apple-m1-big-sur-and-arm64

```
I also had issues installing node-sass on M1, and ended up using the opportunity to replace it with sass, as recommended on the LibSass deprecation notice.

https://sass-lang.com/blog/libsass-is-deprecated

    If you’re a user of Node Sass, migrating to Dart Sass is straightforward: just replace node-sass in your package.json file with sass. Both packages expose the same JavaScript API.

As mentioned by [@Ti Hausmann](https://stackoverflow.com/users/860205/ti-hausmann) you can try with:

npm uninstall node-sass
npm install --save-dev sass

The replacement was completely smooth, it worked on M1, and I couldn't notice any performance impact locally or on the CI.
```

**Comment by apoapostolov** [comment]
Current available version 1.0.3 keeps pointing at 1.0.2

**Comment by YourFavouriteOreo** [comment]
Should be fixed now , please let me know . Its been a while since I deployed for FVTT so I might have misexecuted something

**Comment by FuriousBottle** [comment]
It's still pointing at 1.0.2 for me.
UPDATE: I was able to update to 1.04 by uninstalling and reinstalling instead of hitting update.
