### ISSUE TITLE
[V10] 1.0.4 has the GIF UI always visible on top of Chat Log

### ISSUE THREAD

**Issue by apoapostolov** [YourFavouriteOreo/VTT-Chat-GIFs#14]
The UI being shown constantly on top of chat log makes the chat unusable.

**Comment by MentalyUnsound** [comment]
![image](https://github.com/YourFavouriteOreo/VTT-Chat-GIFs/assets/4683820/2d802919-3140-4a0a-a142-43f27752410d)
Same thing happening for me.

**Comment by apoapostolov** [comment]
Switch to 1.0.3 and lock to prevent updates.

**Comment by weepingminotaur** [comment]
Same issue occurring for me. Would be nice to get it fixed and also an update for v11 compatibility.

**Comment by Asinphi** [comment]
Should be fixed now, and v11 compatibility is implemented in version 1.1.0.

If you used Custom CSS snippets to fix this issue yourself, might want to remove those.
