### ISSUE TITLE
Chat GIF's doesn't work with the Dice Tray module.

### ISSUE THREAD

**Issue by Peenicks** [YourFavouriteOreo/VTT-Chat-GIFs#2]
Tested on Foundry 0.8.7

**Comment by YourFavouriteOreo** [comment]
Which version of chat gifs?

**Comment by Peenicks** [comment]
Latest version!

**Comment by YourFavouriteOreo** [comment]
show me a screenshot plz

**Comment by Peenicks** [comment]
![2021-06-17 23_40_00-Window](https://user-images.githubusercontent.com/13890194/122475842-89a91a80-cfc5-11eb-91c1-d7485627e2fc.png)

As you click on the GIF icon, that just pops up and doesn't finish.

**Comment by YourFavouriteOreo** [comment]
Please screenshot for me all ur modules. This doesn't seem like the dice
tray module as it works on my side with the dice tray module

**Comment by Peenicks** [comment]
![2021-06-18 11_06_09-Window](https://user-images.githubusercontent.com/13890194/122540019-8135fb80-d028-11eb-832c-218480f5cb88.png)
![2021-06-18 11_06_18-Window](https://user-images.githubusercontent.com/13890194/122540022-82672880-d028-11eb-8de1-ec0f8b3f61c3.png)
![2021-06-18 11_23_05-Window](https://user-images.githubusercontent.com/13890194/122540023-82ffbf00-d028-11eb-97ea-fd7eff235ed1.png)
![2021-06-18 11_24_32-Window](https://user-images.githubusercontent.com/13890194/122540025-82ffbf00-d028-11eb-9f44-669c2187d73a.png)
![2021-06-18 11_28_06-Window](https://user-images.githubusercontent.com/13890194/122540033-84c98280-d028-11eb-9d1a-12cc3fc5d3c2.png)
I also tested with all mods and disabling Dice Tray, GIF module works fine.

Hello, here's a swarm of screenshots, I double tested with just dice tray and GIF module and it seems to be dice tray on my end.

**Comment by YourFavouriteOreo** [comment]
Just released a new version to address this... let me know whether it addresses ur issue

**Comment by Peenicks** [comment]
Working! Thanks for the quick fix!
