### ISSUE TITLE
Chat GIF doesn't show hidden monsters in initiative tracker.

### ISSUE THREAD

**Issue by Peenicks** [YourFavouriteOreo/VTT-Chat-GIFs#3]
For whatever reason Chat GIF seems to completely hide monsters from the initiative tracker when they are hidden
![2021-06-20 11_22_44-Window](https://user-images.githubusercontent.com/13890194/122668767-f84ec980-d1b9-11eb-8123-78e1a02ffa0c.png)
![2021-06-20 11_23_35-Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application - Opera](https://user-images.githubusercontent.com/13890194/122668768-fa188d00-d1b9-11eb-86a6-917180d4efee.png)

Mod list is only Chat GIF for the purposes of this test.
Foundry ver. 0.8.7

**Comment by apetina** [comment]
I can confirm same issue in Foundry 0.8.8 in Pathfinder 1 system. Combatant disappears too when made invisible from combat tracker.

**Comment by rbl047** [comment]
Same issue here. Using D&D 5e on foundry 0.8.8, when I click the "visibility" button on the combat tracker, the character disappears from the list. The only way to put it back on the combat tracker is to go to the token on the map and click on visibility button.

**Comment by brunocalado** [comment]
Maybe add libwrapper can help with this

**Comment by happy-cujo** [comment]
The CSS are not scoped correctly. There is a definition for `.hidden` class (and few different ones) that is used in vanilla Foundry to mark combatant as hidden. This module overrides it and sets it's attributes as `display: none;` hence the disappearance of the combatant. 

The CSS selectors should be scoped to `#gifSearch` or different class that identifies module part/block.

**Comment by tehguitarist** [comment]
Made a PR #9 which should fix this.

**Comment by YourFavouriteOreo** [comment]
v1.0.3 released should fix this
