### ISSUE TITLE
Unable to update the module

### ISSUE THREAD

**Issue by happy-cujo** [YourFavouriteOreo/VTT-Chat-GIFs#4]
## Configuration
- Foundry VTT 0.8.8

## Steps to reproduce
1. Install module via in-app module manager
2. Try to update it

## Expected
Module is updated successfully

## Actual
![image](https://user-images.githubusercontent.com/15898113/127142892-e896b8b7-38a8-48a4-a166-29dc5abfb9e8.png)

## Notes
I need to remove the module completely and install it again via in-app module manager in order to get the most recent version.
The [link](https://github.com/YourFavouriteOreo/VTT-Chat-GIFs/releases/download/lastest/dist/module.json) from the error message returns 404 not found error.

**Comment by Asinphi** [comment]
Will be fixed after manually updating to 1.1.0 or higher using the module.json link. After that, you should be able to update to future versions without hassle.
