### ISSUE TITLE
[Suggestion] Size/Width button

### ISSUE THREAD

**Issue by RafaCBarros** [YourFavouriteOreo/VTT-Chat-GIFs#7]
Really simple stuff, but... change the width of `#gifButton` to `auto` or `fit-content`.

Current button (`width:1.75rem`)
![image](https://user-images.githubusercontent.com/82919168/149568540-05756ae6-adcb-4320-be6b-6dd1368dded5.png)
Suggestion (`width:auto`)
![image](https://user-images.githubusercontent.com/82919168/149568662-35eddbf7-0db4-425d-a443-effaef09d926.png)

**Comment by tehguitarist** [comment]
Made a PR #9 which should fix this.

**Comment by YourFavouriteOreo** [comment]
v1.0.3 released should fix this
