### ISSUE TITLE
V10 - module hides A/V controls whilst docked.

### ISSUE THREAD

**Issue by tehguitarist** [YourFavouriteOreo/VTT-Chat-GIFs#8]
This looks like it is linked to issue #3 (in terms of scoping). 

Whilst AV windows are docked (doesn't matter to the sides or bottom) the controls/settings all get hidden when this module is active.

Tested with all other modules disabled to narrow it down.

**Comment by tehguitarist** [comment]
Made a PR #9 which should fix this.

**Comment by YourFavouriteOreo** [comment]
v1.0.3 released should fix this
